### ISSUE TITLE
视频播放的功能建议和疑问

### ISSUE THREAD

**Issue by redstoneleo** [sonichy/Android_HTYBrowser#2]
（1）不知道视频独立播放到底是什么功能，希望解释一下
（2）建议屏幕关闭之后还可以让视频播放——有些视频我们只用来听音频，没必要看画面
（3）如果可以的话希望做一个视频的增强投屏功能（我的理解是把线上缓存到本机的视频投屏到电视上），如UC浏览器那种（如图所示），UC浏览器不支持投屏YouTube，而投屏到电视上看YouTube也还是有很多人需要的，希望大大考虑下。我不会APP开发，但是懂一些交互设计，所以如果需要我帮忙的话我们可以在这里交流
![image](https://user-images.githubusercontent.com/5896180/94170017-17862800-fec2-11ea-8ee4-99c219dacbf8.png)

**Comment by sonichy** [comment]
1.独立视频播放的意思是，尝试提取网页视频地址，直接打开，然后可以全屏和保存，设计目的是为了保存。
2.屏幕关闭之后还让视频播放，产品经理肯定不会同意的，如果有需求的话，可以考虑做一个设置允许。
3.投屏肯定是不会的，太复杂了，做了也会造成安装包变很大，一般会交给系统的投屏软件处理。

**Comment by redstoneleo** [comment]
关于第二点，哔哩哔哩APP就是这么做的，“做一个设置允许”也很好

**Comment by sonichy** [comment]
今天试了一下，APP后台WebView里的视频会自动暂停，后台不暂停可能只存在于老版系统中（Android4？）或某些网站，因为我的确在代码里写了手动暂停。
